export const Districts = [
  {
    province: "SudurPaschim",
    label: "Achham",
    value: "1",
    cities: [
      { label: "Bayalpata" },
      { label: "Bhatakatiya" },
      { label: "Chaurpati" },
      { label: "Dhakari" },
      { label: "Jayagadh" },
      { label: "Kalagaun" },
      { label: "Kamal bazar" },
      { label: "Kuchikot" },
      { label: "Mellekh" },
      { label: "Srikot" },
      { label: "Thanti" },
      { label: "Turmakhad" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Baitadi",
    value: "2",
    cities: [
      { label: "Dehimandau" },
      { label: "Dhungad" },
      { label: "Dilasaini" },
      { label: "Gajari Changgad" },
      { label: "Kesharpur" },
      { label: "Khodpe" },
      { label: "Mulkhatali" },
      { label: "Patan" },
      { label: "Purchaudihat" },
      { label: "Sharmali" },
      { label: "Sitad" },
      { label: "Srikot" },
      { label: "Swopana Taladehi" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Bajhang",
    value: "3",
    cities: [
      { label: "Bungal" },
      { label: "Chaudhari" },
      { label: "Chhanna" },
      { label: "Jamatola" },
      { label: "Jaya Prithivi Nagar" },
      { label: "Rayal" },
      { label: "Shayadi" },
      { label: "Talkot" },
      { label: "Thalara" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Bajura",
    value: "4",
    cities: [
      { label: "Chhatara" },
      { label: "Dandakot" },
      { label: "Dogadi" },
      { label: "Faiti" },
      { label: "Jukot" },
      { label: "Kolti" },
      { label: "Manakot" },
      { label: "Tate" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Dadeldhura",
    value: "5",
    cities: [
      { label: "Ajayameru" },
      { label: "Chipur" },
      { label: "Dandaban" },
      { label: "Gaira Ganesh" },
      { label: "Ganeshpur" },
      { label: "Jogbudha" },
      { label: "Lamikande" },
      { label: "Ugratara" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Darchula",
    value: "6",
    cities: [
      { label: "Dandakot" },
      { label: "Duhuti" },
      { label: "Gokule" },
      { label: "Joljibi" },
      { label: "Malikarjun" },
      { label: "Marmalatinath" },
      { label: "Rapla" },
      { label: "Ritha Chaupata" },
      { label: "Sipti" },
      { label: "Sitola" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Doti",
    value: "7",
    cities: [
      { label: "Banedungrasen" },
      { label: "Boktan" },
      { label: "Byal" },
      { label: "Daund" },
      { label: "Gadhshera" },
      { label: "Jorayal" },
      { label: "Lanakedareswor" },
      { label: "Mauwa Nagardaha" },
      { label: "Mudbhara" },
      { label: "Sanagaun" },
      { label: "Silgadhi" },
    ],
  },
  {
    province: "SudurPaschim",
    label: "Kailali",
    value: "8",
    cities: [
      { label: "Atariya" },
      { label: "Bhajani" },
      { label: "Chaumala" },
      { label: "Dododhara" },
      { label: "Hasuliya" },
      { label: "Joshipur" },
      { label: "Lamki" },
      { label: "Masuriya" },
      { label: "Pahalmanpur" },
      { label: "Phaltude" },
      { label: "Phulbari" },
      { label: "Tikapur" },
    ],
  },
  {
    value: "9",
    province: "SudurPaschim",
    label: "Kanchanpur",
    cities: [
      { label: "Airport" },
      { label: "Beldadi" },
      { label: "Chandani" },
      { label: "Jhalari" },
      { label: "Kalika" },
      { label: "Kanchanpur" },
      { label: "Krishnapur" },
      { label: "Pipaladi" },
      { label: "Punarbas" },
      { label: "Suda" },
    ],
  },
  {
    value: "10",
    province: "Province No. 5",
    label: "Arghakhanchi",
    cities: [
      { label: "Argha" },
      { label: "Arghatosh" },
      { label: "Balkot" },
      { label: "Dhikura" },
      { label: "Hamshapur" },
      { label: "Khana" },
      { label: "Khidim" },
      { label: "Khilji" },
      { label: "Pali" },
      { label: "Subarnakhal" },
      { label: "Thada" },
      { label: "Wangla" },
    ],
  },
  {
    province: "Province No. 5",
    label: "Banke",
    value: "11",
    cities: [
      { label: "Bhojbhagawanpur" },
      { label: "Chandranagar" },
      { label: "Chisapani" },
      { label: "Godahana" },
      { label: "Jayaspur" },
      { label: "Khajura" },
      { label: "Khaskusma" },
      { label: "Kohalapur" },
      { label: "Ramjha" },
      { label: "Suiya" },
      { label: "Udayapur" },
    ],
  },
  {
    province: "Province No. 5",
    label: "Bardiya",
    value: "12",
    cities: [
      { label: "Baganaha" },
      { label: "Bhurigaun" },
      { label: "Jamuni" },
      { label: "Magaragadi" },
      { label: "Mainapokhar" },
      { label: "Motipur" },
      { label: "Pashupatinagar" },
      { label: "Rajapur" },
      { label: "Sanoshri" },
    ],
  },
  {
    province: "Province No. 5",
    label: "Dang",
    cities: [
      "Bhaluwang",
      "Ghoraha",
      "Hapur",
      "Hekuli",
      "Jangrahawa",
      "Jumlepani",
      "Koilabas",
      "Lamahi",
      "Manpur",
      "Panchakule",
      "Rampur",
      "Shantinagar",
      "Tulsipur",
      "Urahari",
    ],
  },
  { province: "Province No. 5", label: "Eastern Rukum", cities: [] },
  {
    province: "Province No. 5",
    label: "Gulmi",
    cities: [
      "Arje",
      "Bharse",
      "Birabas",
      "Chandrakot",
      "Dhurkot",
      "Ismadohali",
      "Majuwa",
      "Manabhak",
      "Pipaldanda",
      "Purkotadha",
      "Purtighat",
      "Ridi",
      "Sringa",
      "Wami",
    ],
  },
  { province: "Province No. 5", label: "Kapilvastu", cities: [] },
  {
    province: "Province No. 5",
    label: "Palpa",
    cities: [
      "Argali",
      "Aryabhanjyang",
      "Baldengadi",
      "Chhahara",
      "Hungi",
      "Jalpa",
      "Jhadewa",
      "Khasyauli",
      "Madanpokhara",
      "Palungmainadi",
      "Rampur",
      "Sahalkot",
      "Tahu",
    ],
  },
  { province: "Province No. 5", label: "Parasi", cities: [] },
  {
    province: "Province No. 5",
    label: "Pyuthan",
    cities: [
      "Baraula",
      "Bhingri",
      "Bijuwar",
      "Dakhaquadi",
      "Lungbahane",
      "Machchhi",
      "Majuwa",
      "Naya Gaun",
      "Thulabesi",
      "Wangesal",
    ],
  },
  {
    province: "Province No. 5",
    label: "Rolpa",
    cities: [
      "Dahaban",
      "Ghartigaun",
      "Himtakura",
      "Jhenam (Holeri)",
      "Khungri",
      "Nerpa",
      "Shulichaur",
      "Sirpa",
      "Thawang",
    ],
  },
  {
    province: "Province No. 5",
    label: "Rupandehi",
    cities: [
      "Amuwa",
      "Betkuiya",
      "Butwal",
      "Dhakadhai",
      "Kotihawa",
      "Lumbini",
      "Mahadehiya",
      "Manigram",
      "Parroha",
      "Saljhandi",
      "Sauraha Pharsa",
      "Siktahan",
      "Suryapura",
      "Tenuhawa",
      "Thutipipal",
    ],
  },
  {
    province: "Gandaki",
    label: "Baglung",
    cities: [
      "Arnakot",
      "Balewa Payupata",
      "Bereng",
      "Bihukot",
      "Bongadovan",
      "Galkot",
      "Harichaur",
      "Jaidi Belbagar",
      "Jhimpa",
      "Khrwang",
      "Kusmi Shera",
      "Pala",
      "Pandavkhani",
    ],
  },
  {
    province: "Gandaki",
    label: "Gorkha",
    cities: [
      "Aarughat",
      "Anapipal",
      "Batase",
      "Bhachchek",
      "Bungkot",
      "Ghyampesal",
      "Gumda",
      "Jaubari",
      "Luintel",
      "Manakamana",
      "Saurpani",
      "Sirdibash",
    ],
  },
  {
    province: "Gandaki",
    label: "Kaski",
    cities: [
      "Bhalam",
      "Birethanti",
      "Chapakot",
      "Gagan Gaunda",
      "Ghachok",
      "Majhathana",
      "Makaikhola",
      "Naudanda",
      "Nirmalpokhari",
      "Pardibandh",
      "Purunchaur",
      "Rupakot",
      "Sildujure",
    ],
  },
  {
    province: "Gandaki",
    label: "Lamjung",
    cities: [
      "Bharate",
      "Gaunda",
      "Gilung",
      "Khudi",
      "Kunchha",
      "Maling",
      "Phaliyasanghu",
      "Sotipasal",
      "Sundar Bazar",
      "Tarkughat",
    ],
  },
  {
    province: "Gandaki",
    label: "Manang",
    cities: ["Bhakra", "Dharapani", "Mathillo Manang", "Nar", "Pisang"],
  },
  {
    province: "Gandaki",
    label: "Mustang",
    cities: [
      "Charang",
      "Chhoser",
      "Kagbeni",
      "Lete",
      "Marpha",
      "Muktinath",
      "Mustang",
      "Thak Tukuche",
    ],
  },
  {
    province: "Gandaki",
    label: "Myagdi",
    cities: [
      "Babiyachaur",
      "Dana",
      "Darbang",
      "Galeswor",
      "Lulang",
      "Pakhapani",
      "Rakhu Bhagawati",
      "Sikha",
      "Takam",
      "Xyamarukot",
    ],
  },
  { province: "Gandaki", label: "Nawalpur", cities: [] },
  {
    province: "Gandaki",
    label: "Parbat",
    cities: [
      "Bachchha",
      "Deurali",
      "Devisthan",
      "Hubas",
      "Karkineta",
      "Khor Pokhara",
      "Khurkot",
      "Lankhudeurali",
      "Salija",
      "Setibeni",
      "Thulipokhari",
    ],
  },
  { province: "Gandaki", label: "Syangja", cities: [] },
  {
    province: "Gandaki",
    label: "Tanahun",
    cities: [
      "Aanbu Khaireni",
      "Baidi",
      "Bandipur",
      "Bhimad",
      "Devaghat",
      "Dumre",
      "Ghiring Sundhara",
      "Kahunshivapur",
      "Khairenitar",
      "Lamagaun",
      "Manechauka",
      "Rising Ranipokhari",
      "Shisha Ghat",
      "Tuhure Pasal",
    ],
  },
  {
    province: "Province No. 2",
    label: "Bara",
    cities: [
      "Amalekhgunj",
      "Bariyarpur",
      "Basantapur",
      "Dumarwana",
      "Jeetpur (Bhavanipur)",
      "Kabahigoth",
      "Mahendra Adarsha",
      "Nijgadh",
      "Parsoni",
      "Pipradhigoth",
      "Simara",
      "Simraungadh",
      "Umjan",
    ],
  },
  {
    province: "Province No. 2",
    label: "Dhanusha",
    cities: [
      "Bagachauda",
      "Chakkar",
      "Dhalkebar",
      "Dhanushadham",
      "Duhabi",
      "Godar Chisapani",
      "Jatahi",
      "Khajuri",
      "Phulgama",
      "Raghunathpur",
      "Sankhuwa Mahendranagar",
      "Tinkoriya",
      "Yadukuha",
    ],
  },
  {
    province: "Province No. 2",
    label: "Mahottari",
    cities: [
      "Balawa",
      "Bardibash",
      "Bhangaha",
      "Gaushala",
      "Laxminiya",
      "Loharpatti",
      "Manara",
      "Matihani",
      "Pipara",
      "Ramgopalpur",
      "Samsi",
      "Shreepur",
    ],
  },
  {
    province: "Province No. 2",
    label: "Parsa",
    cities: [
      "Aadarshanagar",
      "Bahuari Pidari",
      "Bindabasini",
      "Biruwaguthi",
      "Janakitol",
      "Jeetpur",
      "Pakahamainpur",
      "Parbanipur",
      "Paterwa Sugauli",
      "Phokhariya",
      "Ranigunj",
      "Shirsiya Khalwatola",
      "Thori",
      "Viswa",
    ],
  },
  {
    province: "Province No. 2",
    label: "Rautahat",
    cities: [
      "Chandra Nigahapur",
      "Katahariya",
      "Laxminiya",
      "Madhopur",
      "Patharabudhram",
      "Pipra bazar",
      "Rajpurpharahadawa",
      "Samanpur",
      "Saruatha",
      "Shivanagar",
      "Sitalpur",
    ],
  },
  {
    province: "Province No. 2",
    label: "Saptari",
    cities: [
      "Arnaha",
      "Bairaba",
      "Bhagawatpur",
      "Bhardaha",
      "Bishnupur",
      "Bodebarsain",
      "Chhinnamasta",
      "Hanuman Nagar",
      "Kadarwona",
      "Kalyanpur",
      "Kanchanpur",
      "Koiladi",
      "Pato",
      "Phattepur",
      "Praswani",
      "Rupani",
      "Sisawa",
    ],
  },
  {
    province: "Province No. 2",
    label: "Sarlahi",
    cities: [
      "Barahathawa",
      "Bayalbas",
      "Brahmapuri",
      "Chhatauna",
      "Dumariya",
      "Hariaun",
      "Haripur",
      "Haripurwa",
      "Harkathawa",
      "Karmaiya",
      "Kaudena",
      "Lalbandi",
      "Ramnagar(Bahuarwa)",
      "Sundarpur",
    ],
  },
  {
    province: "Province No. 2",
    label: "Siraha",
    cities: [
      "Bandipur",
      "Bariyarpatti",
      "Bastipur",
      "Belha",
      "Bhagawanpur",
      "Bishnupur",
      "Dhanagadhi",
      "Golbazar (Asanpur)",
      "Kalyanpur",
      "Lahan",
      "Madar",
      "Maheshpur patari",
      "Mirchaiya",
      "Sukhipur",
    ],
  },
  {
    province: "Province No. 3",
    label: "Bhaktapur",
    cities: [
      "Dibyashwori",
      "Dubakot",
      "Gamcha",
      "Jorpati",
      "Kharipati",
      "Nagarkot",
      "Tathali",
      "Thimi",
    ],
  },
  {
    province: "Province No. 3",
    label: "Chitwan",
    cities: ["Jutpani", "Khairahani", "Meghauli", "Patihani", "Phulbari"],
  },
  {
    province: "Province No. 3",
    label: "Dhading",
    cities: [
      "Bhumisthan",
      "Gajuri",
      "Katunje",
      "Khanikhola",
      "Lapa",
      "Maidi",
      "Malekhu",
      "Phulkharka",
      "Sertung",
      "Sunaulabazar",
      "Sunkhani",
      "Tripureshwor",
    ],
  },
  {
    province: "Province No. 3",
    label: "Dolakha",
    cities: [
      "Bhusapheda",
      "Chitre",
      "Japhekalapani",
      "Jiri",
      "Khahare",
      "Khopachangu",
      "Lamabagar",
      "Melung",
      "Namdu",
      "Sunkhani",
    ],
  },
  {
    province: "Province No. 3",
    label: "Kathmandu",
    cities: [
      "Balaju",
      "Baluwatar",
      "Bansbari",
      "Budhanilkantha",
      "Chabahil",
      "Dillibazar",
      "Gauchar",
      "Kalimati",
      "Kirtipur",
      "Manmaiju",
      "Pashupati",
      "Pharping",
      "Sachibalaya",
      "Sankhu",
      "Sarbochcha Adalat",
      "Sundarijal",
      "Swayambhu",
      "Thankot",
      "Tokha Saraswati",
      "Tribhuvan University",
    ],
  },
  {
    province: "Province No. 3",
    label: "Kavrepalanchok",
    cities: [
      "Banepa",
      "Dapcha",
      "Dolal Ghat",
      "Ghartichhap",
      "Mangaltar",
      "Panauti",
      "Panchkhal",
      "Phalante",
    ],
  },
  {
    province: "Province No. 3",
    label: "Lalitpur",
    cities: [
      "Bhattedanda",
      "Chapagaun",
      "Darabartole",
      "Dhapakhel",
      "Godawari",
      "Gotikhel",
      "Imadol",
      "Lubhu",
      "Pyutar",
    ],
  },
  { province: "Province No. 3", label: "Makwanpur", cities: [] },
  {
    province: "Province No. 3",
    label: "Nuwakot",
    cities: [
      "Bhadratar",
      "Chokade",
      "Deurali",
      "Devighat",
      "Kahule",
      "Kharanitar",
      "Nuwakot",
      "Pokharichapadanda",
      "Ramabati",
      "Ranipauwa",
      "Rautbesi",
      "Taruka",
      "Thansingh",
    ],
  },
  {
    province: "Province No. 3",
    label: "Ramechhap",
    cities: [
      "Betali",
      "Bhirpani",
      "Doramba",
      "Duragaun",
      "Hiledevi",
      "Kathjor",
      "Khimti",
      "Puranagaun",
      "Saghutar",
      "Those",
    ],
  },
  {
    province: "Province No. 3",
    label: "Rasuwa",
    cities: ["Dhaibung", "Ramkali", "Rasuwa", "Syaphru Besi"],
  },
  {
    province: "Province No. 3",
    label: "Sindhuli",
    cities: [
      "Bahun Tilpung",
      "Belghari",
      "Bhiman",
      "Dakaha",
      "Dudhauli",
      "Gwaltar",
      "Jhanga Jholi",
      "Kapilakot",
      "Khurkot",
      "Netrakali",
      "Pipalmadhiratanpur",
      "Solpa",
    ],
  },
  {
    province: "Province No. 3",
    label: "Sindhupalchok",
    cities: [
      "Atarpur",
      "Balephi",
      "Barabise",
      "Bhotsipa",
      "Dubachaur",
      "Gyalthum",
      "Jalbire",
      "Kodari",
      "Lamosanghu",
      "Melamchi Bahunepati",
      "Nawalpur",
      "Pangtang",
      "Thangapaldhap",
    ],
  },
  {
    province: "Province No. 1",
    label: "Bhojpur",
    cities: [
      "Baikunthe",
      "Bastim",
      "Bhulke",
      "Deurali",
      "Dilpa Annapurna",
      "Dingla",
      "Dobhane",
      "Kulung Agrakhe",
      "Pyauli",
      "Ranibas",
      "Timma",
      "Tiwari Bhanjyang",
      "Walangkha",
      "Yaku",
    ],
  },
  {
    province: "Province No. 1",
    label: "Dhankuta",
    cities: [
      "Ankhisalla",
      "Arknaule",
      "Bhedetar",
      "Chungmang",
      "Dandabazar",
      "Dhankuta",
      "Hile",
      "Leguwa",
      "Mare Katahare",
      "Mudhebash",
      "Muga",
      "Pakhribash",
      "Rajarani",
      "Teliya",
    ],
  },
  {
    province: "Province No. 1",
    label: "Ilam",
    cities: [
      "Aaitabare",
      "Cheesa Pani Panchami",
      "Gajurmukhi",
      "Gitpur",
      "Harkatebazar",
      "Jamuna",
      "Mangal Bare",
      "Nayabazar",
      "Nepaltar",
      "Pashupatinagar",
      "Phikal",
    ],
  },
  {
    province: "Province No. 1",
    label: "Jhapa",
    cities: [
      "Baniyani",
      "Birtamod",
      "Budhabare",
      "Chandragadhi",
      "Damak",
      "Dhulabari",
      "Dudhe",
      "Durgapur",
      "Gauradaha",
      "Gaurigunj",
      "Goldhap",
      "Jhapa",
      "Kankarbhitta",
      "Rajgadh",
      "Sanishchare",
      "Shivagunj",
      "Topagachhi",
    ],
  },
  {
    province: "Province No. 1",
    label: "Khotang",
    cities: [
      "Aiselukharka",
      "Buipa",
      "Chisapani",
      "Halesi mahadevasthan",
      "Jalpa",
      "Khotang",
      "Lamidanda",
      "Manebhanjyang",
      "Sapteshworichhitapokhari",
      "Simpani",
      "Wakshila",
    ],
  },
  {
    province: "Province No. 1",
    label: "Morang",
    cities: [
      "Banigama",
      "Bansbari",
      "Bayarban",
      "Bhaudaha",
      "Biratnagar Bazar",
      "Chunimari",
      "Dadarberiya",
      "Haraincha",
      "Jhorahat",
      "Kerabari",
      "Letang",
      "Madhumalla",
      "Rangeli",
      "Rani Sikiyahi",
      "Sanischare",
      "Sorabhag",
      "Urlabari",
    ],
  },
  {
    province: "Province No. 1",
    label: "Okhaldhunga",
    cities: [
      "Bigutar",
      "Chyanam",
      "Gamanangtar",
      "Ghorakhori",
      "Khani Bhanjyang",
      "Khiji Phalate",
      "Mane Bhanjyang",
      "Moli",
      "Ragani",
      "Rampur",
      "Rumjatar",
    ],
  },
  {
    province: "Province No. 1",
    label: "Panchthar",
    cities: [
      "Ambarpur",
      "Chyangthapu",
      "Limba",
      "Mauwa",
      "Medibung",
      "Mehelbote",
      "Namluwa",
      "Nawamidanda",
      "Rabi",
      "Yangnam",
      "Yasok",
    ],
  },
  {
    province: "Province No. 1",
    label: "Sankhuwasabha",
    cities: [
      "Ankhibhui",
      "Bahrabishe",
      "Chainpur",
      "Chandanpur",
      "Hatiya",
      "Hedangana",
      "Madi",
      "Mamling",
      "Manebhanjyang",
      "Shidhakali",
      "Tamku",
      "Tumlingtar",
      "Wana",
    ],
  },
  {
    province: "Province No. 1",
    label: "Solukhumbu",
    cities: [
      "Himaganga",
      "Jubu",
      "Lukla",
      "Namche Bazar",
      "Necha",
      "Nele",
      "Shishakhola",
      "Sotang",
    ],
  },
  {
    province: "Province No. 1",
    label: "Sunsari",
    cities: [
      "Aurabari",
      "Bakalauri",
      "Bhutaha",
      "Chatara",
      "Chhitaha",
      "Chimadi",
      "Dewangunj",
      "Dharan",
      "Duhabi",
      "Inarauwa",
      "Itahari",
      "Jhumka",
      "Laukahee",
      "Madhuvan",
      "Mahendra Nagar",
      "Mangalbare",
      "Simariya",
    ],
  },
  {
    province: "Province No. 1",
    label: "Taplejung",
    cities: [
      "Change",
      "Dobhan",
      "Hangpang",
      "Khokling",
      "Olangchunggola",
      "Pedang",
      "Sadeba",
      "Sinam",
      "Siwang",
      "Taplejung",
      "Thechambu",
      "Thokimba",
    ],
  },
  {
    province: "Province No. 1",
    label: "Terhathum",
    cities: [
      "Basantapur",
      "Hamarjung",
      "Iwa",
      "Jirikhimti",
      "Morahang",
      "Mulpani",
      "Pokalawang",
      "Sudap",
      "Tinjure",
    ],
  },
  {
    province: "Province No. 1",
    label: "Udayapur",
    cities: [
      "Baraha",
      "Beltar",
      "Bhutar",
      "Hadiya",
      "Katari",
      "Pokhari",
      "Rampur Jhilke",
      "Ratapani (Thoksila)",
      "Rauta Murkuchi",
      "Sorung Chhabise",
      "Udayapur Gadhi",
    ],
  },
  {
    province: "Karnali",
    label: "Dailekh",
    cities: [
      "Byastada",
      "Dhungeshwor",
      "Dullu",
      "Gaidabaj",
      "Jambu Kandha",
      "Malika",
      "Naumule",
      "Rakam Karnali",
    ],
  },
  {
    province: "Karnali",
    label: "Dolpa",
    cities: [
      "Foksundo",
      "Juphal",
      "Kaigaun",
      "Liku",
      "Namdo",
      "Sarmi",
      "Tripurakot",
    ],
  },
  {
    province: "Karnali",
    label: "Humla",
    cities: ["Darma", "Lali", "Muchu", "Sarkegadh", "Srinagar"],
  },
  {
    province: "Karnali",
    label: "Jajarkot",
    cities: [
      "Dalli",
      "Dashera",
      "Dhime",
      "Garkhakot",
      "Karkigaun",
      "Ragda",
      "Rokaya gaun (Limsa)",
      "Thalaraikar",
    ],
  },
  {
    province: "Karnali",
    label: "Jumla",
    cities: [
      "Chautha",
      "Dillichaur",
      "Hatsinja",
      "Kalikakhetu",
      "Malikathata",
      "Narakot",
      "Tatopani",
    ],
  },
  {
    province: "Karnali",
    label: "Kalikot",
    cities: [
      "Jubitha",
      "Kalikot",
      "Kotbada",
      "Mehalmudi",
      "Padamghat",
      "Sanniraskot",
      "Thirpu",
    ],
  },
  {
    province: "Karnali",
    label: "Mugu",
    cities: [
      "Dhainkot",
      "Gumtha",
      "Pulu",
      "Rara",
      "Rowa",
      "Sorubarma",
      "Sukhadhik",
    ],
  },
  {
    province: "Karnali",
    label: "Salyan",
    cities: [
      "Bhalchaur",
      "Dhanbang",
      "Kalimati Kalche",
      "Luham",
      "Mahaneta",
      "Maidu",
      "Malneta",
      "Ragechour",
      "Tharmare",
    ],
  },
  {
    province: "Karnali",
    label: "Surkhet",
    cities: [
      "Babiyachaur",
      "Bheriganga",
      "Chhinchu",
      "Garpan",
      "Gumi",
      "Gutu",
      "Kunathari",
      "Matela",
      "Ramghat",
      "Sahare",
    ],
  },
  { province: "Karnali", label: "Western Rukum", cities: [] },
];
